/**
 * StudyLog Model
 * Represents a study session log entry
 * Matches the backend StudyLog entity structure
 */
export interface StudyLog {
  id?: string;                    // Optional for new logs (MongoDB generates this)
  subject: string;                // Required: Subject name (e.g., "Mathematics")
  topic: string;                  // Required: Specific topic (e.g., "Calculus")
  duration: number;               // Required: Duration in minutes (must be positive)
  date: string;                   // Required: Date in ISO format (YYYY-MM-DD)
  notes?: string;                 // Optional: Additional notes about the study session
}

/**
 * DTO for creating a new StudyLog
 * Excludes the id field since it's generated by the backend
 */
export interface CreateStudyLogDto {
  subject: string;
  topic: string;
  duration: number;
  date: string;
  notes?: string;
}

/**
 * DTO for updating an existing StudyLog
 * All fields are required except notes
 */
export interface UpdateStudyLogDto {
  subject: string;
  topic: string;
  duration: number;
  date: string;
  notes?: string;
}
